version: '3.8'

services:
  db:
    container_name: go-bookstore-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
